development:
  FACEBOOK_CONSUMER_KEY: 1486804751548096
  FACEBOOK_CONSUMER_SECRET: 5b299e3487d3ba2b467de0c7e2cef4c3
  TWITTER_CONSUMER_KEY: YOUR_TWITTER_KEY
  TWITTER_CONSUMER_SECRET: YOUR_TWITTER_SECRET
  GITHUB_CONSUMER_KEY: YOUR_GITHUB_KEY
  GITHUB_CONSUMER_SECRET: YOUR_GITHUB_SECRET
