development:
  FACEBOOK_CONSUMER_KEY: 1513566692205235
  FACEBOOK_CONSUMER_SECRET: 24293874a6ed91c95d277e37dd580039
  TWITTER_CONSUMER_KEY: A3Xx9GwlRMu98B2x5NeeW8bTD
  TWITTER_CONSUMER_SECRET: 6x08Fjer5ZzGXyF3eSVPlba03aMtWKiYmsUOf2u39NxyckdOWq
  GITHUB_CONSUMER_KEY: 2b38b221b641027da949
  GITHUB_CONSUMER_SECRET: ea1bc262681bcc64e28cfbfb3760800a4f089db2
  HATENA_CONSUMER_KEY: Cjoie59SjBoTPw==
  HATENA_CONSUMER_SECRET: 31fNi/vFrIrDW2KEVSKnaGEr4OQ=

